In [246]:
#k-katlamalı Çapraz Doğrulama Örneği
import numpy as np
import pandas as pd

In [247]:
import os 

os.chdir(r"C:\Users\PC\Desktop\ders\4.sınıf\yazılım bakım")

df = pd.read_csv("krediVeriseti.csv",delimiter= ';')

# top 10 data / ilk on veri 
df.head()


krediMiktari  yas  evDurumu  aldigi_kredi_sayi telefonDurumu KrediDurumu
0          1169   67  evsahibi                  2           var    krediver
1          5951   22  evsahibi                  1           yok       verme
2          2096   49  evsahibi                  1           yok    krediver
3          7882   45    kiraci                  1           yok    krediver
4          4870   53    kiraci                  2           yok       verme

In [248]:
# male ve female miktarı 
df['KrediDurumu'].value_counts()

krediver    700
verme       300
Name: KrediDurumu, dtype: int64

In [249]:
# datamızın boyutu
df.shape

(1000, 6)

In [250]:
#datadaki kolonlar hakkında boş değer,kolon tipi ve total veriyi döndürür
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
krediMiktari         1000 non-null int64
yas                  1000 non-null int64
evDurumu             1000 non-null object
aldigi_kredi_sayi    1000 non-null int64
telefonDurumu        1000 non-null object
KrediDurumu          1000 non-null object
dtypes: int64(3), object(3)
memory usage: 47.0+ KB


In [251]:
# datadaki kolonlar
print(list(df.columns))

['krediMiktari', 'yas', 'evDurumu', 'aldigi_kredi_sayi', 'telefonDurumu', 'KrediDurumu']


In [252]:
#featurelar arası bağlantı 
df.corr()

krediMiktari       yas  aldigi_kredi_sayi
krediMiktari           1.000000  0.032716           0.020795
yas                    0.032716  1.000000           0.149254
aldigi_kredi_sayi      0.020795  0.149254           1.000000

In [253]:
# simple algorithms(sayısal veri üzerinde basit hesaplamalar) / mean,count,min,max,standard deviation
df.describe()

krediMiktari          yas  aldigi_kredi_sayi
count   1000.000000  1000.000000        1000.000000
mean    3271.258000    35.546000           1.407000
std     2822.736876    11.375469           0.577654
min      250.000000    19.000000           1.000000
25%     1365.500000    27.000000           1.000000
50%     2319.500000    33.000000           1.000000
75%     3972.250000    42.000000           2.000000
max    18424.000000    75.000000           4.000000

In [254]:
df.head()

krediMiktari  yas  evDurumu  aldigi_kredi_sayi telefonDurumu KrediDurumu
0          1169   67  evsahibi                  2           var    krediver
1          5951   22  evsahibi                  1           yok       verme
2          2096   49  evsahibi                  1           yok    krediver
3          7882   45    kiraci                  1           yok    krediver
4          4870   53    kiraci                  2           yok       verme

In [255]:
listdf = list(df["telefonDurumu"])
listdf[0]

'var'

In [256]:
telefonDurumu = []
for j in listdf:
    if j =='var':
        telefonDurumu += [1]
    else :
        telefonDurumu += [0]

telefonDurumu[0]

1

In [257]:

df['telefonDurumu'] = pd.DataFrame(telefonDurumu) 
df.head()

krediMiktari  yas  evDurumu  aldigi_kredi_sayi  telefonDurumu KrediDurumu
0          1169   67  evsahibi                  2              1    krediver
1          5951   22  evsahibi                  1              0       verme
2          2096   49  evsahibi                  1              0    krediver
3          7882   45    kiraci                  1              0    krediver
4          4870   53    kiraci                  2              0       verme

In [258]:
listdf = list(df["evDurumu"])
listdf[0]

'evsahibi'

In [259]:
evDurumu = []
for j in listdf:
    if j =='evsahibi':
        evDurumu += [1]
    else :
        evDurumu += [0]

evDurumu[0]

1

In [260]:

df['evDurumu'] = pd.DataFrame(evDurumu) 
df.head()

krediMiktari  yas  evDurumu  aldigi_kredi_sayi  telefonDurumu KrediDurumu
0          1169   67         1                  2              1    krediver
1          5951   22         1                  1              0       verme
2          2096   49         1                  1              0    krediver
3          7882   45         0                  1              0    krediver
4          4870   53         0                  2              0       verme

In [261]:
df.corr()

krediMiktari       yas  evDurumu  aldigi_kredi_sayi  \
krediMiktari           1.000000  0.032716 -0.117497           0.020795   
yas                    0.032716  1.000000  0.006553           0.149254   
evDurumu              -0.117497  0.006553  1.000000           0.041386   
aldigi_kredi_sayi      0.020795  0.149254  0.041386           1.000000   
telefonDurumu          0.276995  0.145259 -0.036275           0.065553   

                   telefonDurumu  
krediMiktari            0.276995  
yas                     0.145259  
evDurumu               -0.036275  
aldigi_kredi_sayi       0.065553  
telefonDurumu           1.000000

In [262]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn import model_selection

#Eğitim için ilgili öznitlelik değerlerini seç
X = df.iloc[:, :-1].values

#Sınıflandırma öznitelik değerlerini seç
Y = df.iloc[:, -1].values

In [263]:
from sklearn.model_selection import train_test_split # train/test split lib
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2, random_state = 42)

## NB yöntemi

In [264]:
#Naive Bayes modelinin oluşturulması
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [265]:
#NB modelinin K-katlamalı çapraz doğrulama ile ACC değerinin hesaplanması
scoring = 'accuracy'
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)

In [266]:
cv_results

array([0.675 , 0.675 , 0.7375, 0.6   , 0.625 , 0.7   , 0.725 , 0.725 ,
       0.775 , 0.6375])

In [267]:
msg = "%f (%f)" % (cv_results.mean(), cv_results.std())
msg

'0.687500 (0.052440)'

In [268]:


model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score

from sklearn.metrics import accuracy_score
print("ACC: ",accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

    krediver       0.72      0.94      0.82       141
       verme       0.47      0.12      0.19        59

   micro avg       0.70      0.70      0.70       200
   macro avg       0.59      0.53      0.50       200
weighted avg       0.64      0.70      0.63       200

[[133   8]
 [ 52   7]]
ACC:  0.7


## Baseline : 0.7

## Lineer Regresyon

In [269]:
listdf = list(df["KrediDurumu"])
listdf[1]

'verme'

In [270]:
KrediDurumu = []
for j in listdf:
    if j =='krediver':
        KrediDurumu += [1]
    else :
        KrediDurumu += [0]

KrediDurumu[0]

1

In [271]:

df['KrediDurumu'] = pd.DataFrame(KrediDurumu) 
df.head()

krediMiktari  yas  evDurumu  aldigi_kredi_sayi  telefonDurumu  KrediDurumu
0          1169   67         1                  2              1            1
1          5951   22         1                  1              0            0
2          2096   49         1                  1              0            1
3          7882   45         0                  1              0            1
4          4870   53         0                  2              0            0

In [272]:
#Eğitim için ilgili öznitlelik değerlerini seç
X = df.iloc[:, :-1].values

#Sınıflandırma öznitelik değerlerini seç
Y = df.iloc[:, -1].values

In [273]:
X

array([[1169,   67,    1,    2,    1],
       [5951,   22,    1,    1,    0],
       [2096,   49,    1,    1,    0],
       ...,
       [ 804,   38,    1,    1,    0],
       [1845,   23,    0,    1,    1],
       [4576,   27,    1,    1,    0]], dtype=int64)

In [274]:
Y

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [275]:
#normalization / standard
scaler = preprocessing.StandardScaler()

# separate features from label
x_scaled1 = scaler.fit_transform(X)
x_scaled1

C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.74513141,  2.76645648,  0.63444822,  1.02707891,  1.21459768],
       [ 0.94981679, -1.19140394,  0.63444822, -0.704926  , -0.82331789],
       [-0.41656241,  1.18331231,  0.63444822, -0.704926  , -0.82331789],
       ...,
       [-0.87450324,  0.21583532,  0.63444822, -0.704926  , -0.82331789],
       [-0.50552769, -1.10345149, -1.57617276, -0.704926  ,  1.21459768],
       [ 0.46245715, -0.75164167,  0.63444822, -0.704926  , -0.82331789]])

In [280]:
from sklearn.model_selection import train_test_split # train/test split lib
X_train, X_test, y_train, y_test = train_test_split( x_scaled1, Y, test_size=0.2, random_state = 42)

In [281]:
from sklearn.linear_model import LinearRegression # regression lib / lineer reg.

# model eğitme / model fit
reg = LinearRegression().fit(X_train, y_train) 

In [282]:
# estimate y values / y değerlerini tahmin etmek 
y_pred1 = reg.predict(X_test)
y_pred1[0]

0.6546463919978646

In [283]:
from sklearn import metrics # metric / mean square vs. 
from sklearn.metrics import r2_score # metric / r'2 metric 

#r^2 validation 
print('R2 eror(R^2):', r2_score(y_test, y_pred1)) 

R2 eror(R^2): -0.041726630564453915
